kind: Service
apiVersion: v1
metadata:
  name: zookeeper
spec:
  clusterIP: None
  selector:
    app: lbl-zookeeper
  ports:
  - protocol: TCP
    port: 2181
    targetPort: 2181
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: zookeeper
spec:
  selector:
    matchLabels:
      app: lbl-zookeeper
  replicas: 1
  template: 
    metadata:
      labels:
        app: lbl-zookeeper
    spec:
      containers:
      - name: cont-zookeeper
        image: zookeeper:latest
        ports:
        - containerPort: 2181
---
kind: Service
apiVersion: v1
metadata:
  name: kafka
spec:
  clusterIP: None
  selector:
    app: lbl-kafka
  ports:
  - protocol: TCP
    port: 9092
    targetPort: 9092
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: kafka
spec:
  selector:
    matchLabels:
      app: lbl-kafka
  replicas: 1
  template: 
    metadata:
      labels:
        app: lbl-kafka
    spec:
      containers:
      - name: cont-kafka
        image: eitanya/kafka:0.11.0.2
        env:          
        - name: KAFKA_ADVERTISED_HOST_NAME
          value: kafka
        - name: KAFKA_LISTENERS
          value: PLAINTEXT://kafka:9092
        - name: KAFKA_LOG_CLEANUP_POLICY
          value: compact
        - name: KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS
          value: "3000"
        - name: KAFKA_NUM_PARTITIONS
          value: "16"
        - name: KAFKA_LOG_CLEANER_DELETE_RETENTION_MS
          value: "20000"
        - name: KAFKA_LOG_SEGMENT_BYTES
          value: "512000"
        - name: KAFKA_ZOOKEEPER_CONNECTION_TIMEOUT_MS
          value: "4000"
        - name: KAFKA_ZOOKEEPER_SESSION_TIMEOUT_MS
          value: "4000"
        ports:
        - containerPort: 9092
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: big-messages-producer
spec:
  selector:
    matchLabels:
      app: lbl-big-messages-producer
  replicas: 1
  template: 
    metadata:
      labels:
        app: lbl-big-messages-producer
    spec:
      containers:
      - name: cont-big-messages-producer
        image: big-messages-producer:1.0-SNAPSHOT
        env:
        - name: bootstrap.servers
          value: kafka:9092
        - name: TOPIC
          value: mytopic
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: big-messages-consumer
spec:
  selector:
    matchLabels:
      app: lbl-big-messages-consumer
  replicas: 1
  template: 
    metadata:
      labels:
        app: lbl-big-messages-consumer
    spec:
      containers:
      - name: cont-big-messages-consumer
        image: big-messages-consumer:1.0-SNAPSHOT
        env:
        - name: group.id
          value: cool-consumer
        - name: bootstrap.servers
          value: kafka:9092
        - name: TOPIC
          value: mytopic

